spring.application.name=ems-backend
spring.mail.host=hrtektalis@gmail.com
spring.mail.port=587
spring.mail.username=HR-Tektalis
spring.mail.password=hdmc jkdk krvq fiok
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
