spring.application.name=ems-backend
spring.mail.host=hrtektalis@gmail.com
spring.mail.port=587
spring.mail.username=HR-Tektalis
spring.mail.password=hdmc jkdk krvq fiok
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# POSTGRES DATABASE CONFIG
spring.datasource.url=jdbc:postgresql://localhost:5432/Tektalis
spring.datasource.username=postgres
spring.datasource.password=Shanu2005$
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8081
jwt.secret=Z3V2d3dxd3Vpd2V1d2V1aXdlcXVpd2V1cXVpd2V1cXVpd2V1
jwt.expiration=900000
jwt.refreshExpiration=8640000000

logging.level.org.springframework.security=DEBUG